### ISSUE TITLE
Tagging System

### ISSUE THREAD

**Issue by KenEzekiel** [KenEzekiel/sectors_news_endpoint#1]
### Current Condition
Tags are stored in supabase directly, without proper management and curation

### Desired Condition
Proper curation system for the tags, own database and referral

**Comment by akbarmridho** [comment]
- [ ] Create idx_news_tags table and maintain an initial list of curated tags
- [ ] Re-classify current news and fillings tags data
- [ ] Modify get articles endpoint to handle query by tag

Backlog
- User news watchlist by tag
